### ISSUE TITLE
Background images set in frontmatter variable do not exist

### ISSUE THREAD

**Issue by fabrik42** [humansconf/humansconf.org#2]
Not sure if this is work in progress or a bug...

There is a custom frontmatter variable defined for every page ([index](https://github.com/humansconf/humansconf.org/blob/master/index.md#L3), [code-of-conduct](https://github.com/humansconf/humansconf.org/blob/master/code-of-conduct.md#L3)).

The path in this variable is used to [define a background image for an overlay](https://github.com/humansconf/humansconf.org/blob/master/_layouts/page.html#L7) in the page layout.

However, the image files do not exist right now.

Let me know if this is something that needs fixing or if it is just under construction :)

**Comment by benjmin-r** [comment]
It's just under construction :) 
I'm using [a theme](https://themeforest.net/item/hashtag-for-jekyll-an-elegant-blog-theme/7721454) and I didn't yet look for more fitting background images.

However, feel free to suggest images, that you think might be a good fit for the respective pages. The sample images provided in the theme have dimensions of 1200x700px.

I'm leaving this open in case you or someone else wants to suggest background images. Feel free to close this issue though.

**Comment by benjmin-r** [comment]
Well, the missing images annoyed me enough that I searched for some and implemented them in eca5dc990e5ccd9d924a89e6dc9410caa1873132 😄 ... i.e., I'm closing this issue
